### ISSUE TITLE
maybe add a linter for insecure unicode names

### ISSUE THREAD

**Issue by rurban** [akawashiro/sold#6]
Since object files can contain insecure unicode identifiers, and there exist no linters for objects files or libraries yet, maybe add such a check, based on my https://github.com/rurban/libu8ident/. 
I'm working on a C23++/C23 proposal for safe names, but the same must be done for binuils and linkers eventually.

Since you are experts on CFK languages it would make more sense with this project, as you already have a renamer.

**Comment by akawashiro** [comment]
Ooops, I'm really sorry for not noticing for a long time. Although we don't need to check symbol names because we handle only widely used shared libraries, your https://github.com/rurban/libu8ident/ looks interesting. Thank you for your comment.
